name: ${pom.name}
main: tigeax.customwings.CustomWings
author: Tigeax
version: ${pom.version}
api-version: 1.21.1
softdepend:
  - Vault
  - TokenManager
permissions:
  customwings.command:
    default: true
  customwings.setwing:
    default: op
  customwings.preview:
    default: op
  customwings.editor:
    default: op
  customwings.reload:
    default: op
  customwings.takeawaywing:
    default: op
  customwings.show:
    default: op
  customwings.wing.*:
    default: op
  
